name: games
services:
  backend:
    build:
      context: C:\Users\acer\Desktop\Programmazione\Java\games-backend
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:mysql://host.docker.internal:3306/games
    networks:
      - games

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - /app/node_modules
      - .:/app
    networks:
      - games

networks:
  games: